/*
  DON'T MODIFY.
  This module is automatically generated by the generateAssetModules
  script.
*/

export default {
  // Image assets by reference
  adaptiveIcon: require("../../../assets/images/adaptive-icon.png"),
  favicon: require("../../../assets/images/favicon.png"),
  icon: require("../../../assets/images/icon.png"),
  splash: require("../../../assets/images/splash.png"),
  welcomeIlustration: require("../../../assets/images/WelcomeIlustration.jpg"),
};
